<?php

namespace App\Modules\Application\Models;

use App\Library\DataBase\Mysql;
use App\Modules\Application\Library\Enum\AdminPowerMethod as Method;
use App\Modules\Application\Library\Enum\AdminPowerStatus as Status;

class AdminPower extends Mysql\DataBase
{

    /**
     * AdminPower数据模型对应表名
     * @var null|string
     */
    protected static ?string $table = 'admin_power';
    

    /**
     * 该表中所有字段名
     * SHOW COLUMNS FROM `admin_power`
     *
     * @var string[]
     */
    protected static array $columns = ['id', 'url', 'method', 'status', 'label', 'key', 'created_at', 'updated_at'];


    /**
     * 加入权限
     *
     * @param string $url
     * @param Method $method
     * @param Status $status
     * @return bool
     */
    public function push(string $url, Method $method, Status $status): bool
    {
        $url = strtolower(trim($url, '/'));
        if (static::exists('url=? AND method=?', [$url, $method->name])) return false;
        try {
            return $this->insert(['url' => $url, 'method' => $method->name, 'status' => $status->name]);
        } catch (\Exception $e) {
        }
        return false;
    }

    /**
     * 删除一个权限
     *
     * @param int $powerId
     * @return bool
     */
    public function deletePower(int $powerId): bool
    {
        return parent::delete('id=?', [$powerId]) > 0; // TODO: Change the autogenerated stub
    }
}